"""add token_version and index on user type

Revision ID: 3345993e6957
Revises: 0789e411cd49
Create Date: 2026-08-24 22:48:38.326394
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3345993e6957'
down_revision: str | None = '0789e411cd49'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows so this doesn't fail against a
    # non-empty table (a bare NOT NULL ADD COLUMN does, with no default to
    # fill in for rows that already exist).
    op.add_column(
        'users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='1')
    )
    op.create_index(op.f('ix_users_type'), 'users', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_type'), table_name='users')
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
