"""add current_refresh_token_id for refresh token rotation

Revision ID: 33f31207eacd
Revises: 599f1c2ee189
Create Date: 2026-08-25 15:36:36.782745
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f31207eacd'
down_revision: str | None = '599f1c2ee189'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_refresh_token_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_refresh_token_id')
    # ### end Alembic commands ###
