"""add pg_trgm indexes for partial-match filters

Revision ID: 599f1c2ee189
Revises: 3345993e6957
Create Date: 2026-08-25 03:52:38.320156
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599f1c2ee189'
down_revision: str | None = '3345993e6957'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # gin_trgm_ops indexes below depend on this extension. Not something
    # autogenerate can know to add on its own -- extensions aren't part of
    # SQLAlchemy's table metadata, only hand-added here.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_city_trgm', 'users', ['city'], unique=False, postgresql_using='gin', postgresql_ops={'city': 'gin_trgm_ops'})
    op.create_index('ix_users_email_trgm', 'users', ['email'], unique=False, postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops'})
    op.create_index('ix_users_first_name_trgm', 'users', ['first_name'], unique=False, postgresql_using='gin', postgresql_ops={'first_name': 'gin_trgm_ops'})
    op.create_index('ix_users_last_name_trgm', 'users', ['last_name'], unique=False, postgresql_using='gin', postgresql_ops={'last_name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_last_name_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'last_name': 'gin_trgm_ops'})
    op.drop_index('ix_users_first_name_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'first_name': 'gin_trgm_ops'})
    op.drop_index('ix_users_email_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops'})
    op.drop_index('ix_users_city_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'city': 'gin_trgm_ops'})
    # ### end Alembic commands ###
    # Deliberately not dropping the pg_trgm extension -- CREATE EXTENSION
    # IF NOT EXISTS is idempotent and harmless to leave installed, and
    # something else in the DB may come to depend on it later.
